name: Baidu push

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  baidu-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true

      - name: Build
        run: |
          git config core.quotePath false
          hugo

      - name: Install requests
        run: pip install requests

      - name: Push
        run: |
          python <<END
          import requests
          import re

          with open('public/sitemap.xml', 'r') as sitemap:
            pattern = re.compile(r'(?<=<loc>).+?(?=</loc>)')
            result = pattern.findall(sitemap.read())
            req = requests.post('http://data.zz.baidu.com/urls?site=https://yourname.github.io&token=${{ secrets.BAIDU_PUSH_TOKEN }}', '\n'.join(result))
            print(req.text)
          END
